### PR TITLE
improve user experience

### LINKED ISSUE #58: new boilerplate without any frameworks or libraries
In order to replace the original boilerplate which dependent on React or Vue that cause codebase hard to maintain and unfriendly use.

The new boilerplate build up without any frameworks or libraries like react, vue, and angular

This issue will be resolved at https://github.com/PortalNetwork/kaizen-cli/pull/64/commits/4124c19e9044942d986ac97bd6fdd481cf4b272c on PR #64

### PR DESCRIPTION
**Pull request by ahlumin**
to resolve #58, #59 

#### command 
`$ kaizen ipfs upload <file|directory path> `

#### usage
User can specify the path and upload to IPFS.
Should use 'kaizen set-ipfs' to setting IPFS configuration first

* * *
#### command 
`$ kaizen set-ipfs --host <host> --port <port> --protocol <protocol>`
* __host__ - required, e.g. `ipfs.infura.io`
* __port__ - required, e.g. `5001`
* __protocol__ - required, e.g. `https`

#### usage
Setting IPFS configuration for IPFS API usage

* * *
#### command 
`$ kaizen set-ethereum --network <network id> --port <port> --provider <provider>`
* __network__ - required, e.g. `3` which mean Ropsten testnet
* __port__ - required, e.g. `8545`
* __provider__ - required, e.g. `https://ropsten.infura.io/you-infura-key`

#### usage
Setting Ethereum configuration

* * *
#### command 
`$ kaizen set-nkn --identifier <identifier> --private-key <private key> --rpc-server <seed RPC server address>`
* __identifier__ - required,
* __private-key__ - required,
* __rpc-server__ - required,

#### usage
Setting NKN configuration

* * *
#### command 
`kaizen add boilerplate --name <project name> --library <react|vue>`
* __name__ - optional, specify project name. If ignore, default is `new-boilerplate`
* __library__ - optional, specify which library want to add.

### CODE REVIEW

**Comment by PhyrexTsai** [comment]
@ahlumin Is there a way to split the boilerplate outside of this repository, if we combine this whole source code here, it seems too big for this tool at the first time download or install

**Comment by PhyrexTsai** [comment]
@ahlumin Recommend we can download from other side and add config after download

**Comment by ahlumin** [comment]
sure, refactored at https://github.com/PortalNetwork/kaizen-cli/pull/64/commits/afee5d272249af4be4eee2023eb9f4e665a4572f

**Comment by PhyrexTsai** [comment]
@ahlumin 
```
$ kaizen set-ethereum --network <network id> --port <port> --provider <provider>
```
If we use the `infura.io`, the port is not required, since the port forward to the 80 port instead, so maybe we don't need require for the `port`

**Comment by ahlumin** [comment]
maybe `port` should be optional when setting ethereum configuration

**Comment by ahlumin** [comment]
fixed, https://github.com/PortalNetwork/kaizen-cli/pull/64/commits/0dcf60ab829c27a5bd36dd7ce13ba4d4c9373459, https://github.com/PortalNetwork/kaizen-cli/pull/64/commits/5d14dd09cc0509c9a3021b7f1eb0157122a32eaf

**Pull request merged**
